from typing import Any, Callable

AST_ENABLE_ALWAYS: int
DP_RIGHT: int
DP_SZHINT: int
MFF_FAST: int
SETMENU_APP: int


class PluginForm:
    WOPN_PERSIST: int
    WOPN_DP_RIGHT: int
    WOPN_DP_SZHINT: int

    def Show(self, title: str, options: int = ...) -> bool: ...

    @staticmethod
    def FormToPyQtWidget(form: Any) -> Any: ...


class action_handler_t:
    def __init__(self) -> None: ...
    def activate(self, ctx: Any) -> int: ...
    def update(self, ctx: Any) -> int: ...


class action_desc_t:
    def __init__(
        self,
        name: str,
        label: str,
        handler: action_handler_t,
        shortcut: str | None = ...,
        tooltip: str | None = ...,
        icon: int = ...,
    ) -> None: ...


def attach_action_to_menu(menu_path: str, action_name: str, flags: int) -> bool: ...
def close_widget(widget: Any, flags: int) -> None: ...
def detach_action_from_menu(menu_path: str, action_name: str) -> bool: ...
def execute_sync(callback: Callable[[], Any], flags: int) -> Any: ...
def find_widget(title: str) -> Any: ...
def get_curline() -> str | None: ...
def get_current_widget() -> Any: ...
def get_highlight(widget: Any) -> tuple[str, int] | None: ...
def get_screen_ea() -> int: ...
def msg(text: str) -> None: ...
def read_range_selection(view: Any) -> tuple[bool, int, int] | None: ...
def register_action(action_desc: action_desc_t) -> bool: ...
def set_dock_pos(src: str, dest: str, position: int) -> bool: ...
def unregister_action(action_name: str) -> bool: ...
def __getattr__(name: str) -> Any: ...
